ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/java/org/richfaces/book/examples/AutocompleteBean.java
package org.richfaces.book.examples;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class AutocompleteBean {
	private List<String> suggestions = null;

	public AutocompleteBean() {
		suggestions = new ArrayList<String>();
		suggestions.add("Banana");
		suggestions.add("Cranberry");
		suggestions.add("Blueberry");
		suggestions.add("Orange");
		suggestions.add("Apple");
		suggestions.add("Strawberry");
	}

	public List<String> autocomplete(String prefix) {
		List<String> result = new ArrayList<String>();
		for (String suggestion : suggestions) {
			if (suggestion.startsWith(prefix)) {
				result.add(suggestion);
			}
		}
		return result;
	}

	public List<String> getSuggestions() {
		return suggestions;
	}

	public void setSuggestions(List<String> suggestions) {
		this.suggestions = suggestions;
	}
}

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/java/org/richfaces/book/examples/FileUploadBean.java
package org.richfaces.book.examples;

import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.richfaces.event.FileUploadEvent;
import org.richfaces.model.UploadedFile;
@ManagedBean
@SessionScoped
public class FileUploadBean {
	private ArrayList<UploadedFile> files = new ArrayList<UploadedFile>();

	public void paint(OutputStream stream, Object object) throws IOException {
		stream.write(getFiles().get((Integer) object).getData());
	}

	public void listener(FileUploadEvent event) throws Exception {
		UploadedFile item = event.getUploadedFile();
		files.add(item);
	}

	public Date getTimeStamp(){
		return new Date();
	}
	
	// Getters and setters

	public ArrayList<UploadedFile> getFiles() {
		return files;
	}

	public void setFiles(ArrayList<UploadedFile> files) {
		this.files = files;
	}

}

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/java/org/richfaces/book/examples/InplaceInputBean.java
package org.richfaces.book.examples;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@ManagedBean
@RequestScoped
public class InplaceInputBean {

	private String name;
	private String email;

	public void setName(String name) {
		this.name = name;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return name;
	}

	public String getEmail() {
		return email;
	}

}

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/java/org/richfaces/book/examples/SelectBean.java
package org.richfaces.book.examples;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.event.ValueChangeEvent;
import javax.faces.model.SelectItem;

@ManagedBean
@RequestScoped
public class SelectBean {
	private static final String[] FRUITS = { "Banana", "Cranberry",
			"Blueberry", "Orange" };
	private static final String[] VEGETABLES = { "Potatoes", "Broccoli",
			"Garlic", "Carrot" };
	private String currentItem = null;
	private String value = null;
	private String currentType = null;
	private List<SelectItem> firstList = new ArrayList<SelectItem>();
	private List<SelectItem> secondList = new ArrayList<SelectItem>();

	public SelectBean() {
		SelectItem item = new SelectItem("fruits", "Fruits");
		firstList.add(item);
		item = new SelectItem("vegetables", "Vegetables");
		firstList.add(item);
		for (int i = 0; i < FRUITS.length; i++) {
			item = new SelectItem(FRUITS[i]);
		}
	}

	public void valueChanged(ValueChangeEvent event) {
		secondList.clear();
		if (null != event.getNewValue()) {
			String[] currentItems;
			if (((String) event.getNewValue()).equals("fruits")) {
				currentItems = FRUITS;
			} else {
				currentItems = VEGETABLES;
			}
			for (int i = 0; i < currentItems.length; i++) {
				SelectItem item = new SelectItem(currentItems[i]);
				secondList.add(item);
			}
		}
	}

	// Getters and setters
	public String getCurrentItem() {
		return currentItem;
	}

	public void setCurrentItem(String currentItem) {
		this.currentItem = currentItem;
	}

	public String getCurrentType() {
		return currentType;
	}

	public void setCurrentType(String currentType) {
		this.currentType = currentType;
	}

	public List<SelectItem> getFirstList() {
		return firstList;
	}

	public List<SelectItem> getSecondList() {
		return secondList;
	}
	public String getValue() {
		return value;
	}
}

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/java/org/richfaces/book/examples/StatesSuggestionBean.java
package org.richfaces.book.examples;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class StatesSuggestionBean {

	private List<State> statesList;

	private String state; // getter and setter

	@PostConstruct
	public void init() {
		statesList = new ArrayList<State>();
		statesList.add(new State("Alabama", "Montgomery"));
		statesList.add(new State("Alaska", "Juneau"));
		statesList.add(new State("Arizona", "Phoenix"));
		statesList.add(new State("Arkansas", "Little Rock"));
		statesList.add(new State("California", "Sacramento"));
		statesList.add(new State("Colorado", "Denver"));
		statesList.add(new State("Connecticut", "Hartford"));
		statesList.add(new State("Delaware", "Dover"));
		statesList.add(new State("Florida", "Tallahassee"));
		statesList.add(new State("Georgia", "Atlanta"));
		statesList.add(new State("Hawaii", "Honolulu"));
		statesList.add(new State("Idaho", "Boise"));
		statesList.add(new State("Illinois", "Springfield"));
		statesList.add(new State("Indiana", "Indianapolis"));
		statesList.add(new State("Iowa", "Des Moines"));
		statesList.add(new State("Kansas", "Topeka"));
		statesList.add(new State("Kentucky", "Frankfort"));
		statesList.add(new State("Louisiana", "Baton Rouge"));
		statesList.add(new State("Maine", "Augusta"));
		statesList.add(new State("Maryland", "Annapolis"));
		statesList.add(new State("Massachusetts", "Boston"));
		statesList.add(new State("Michigan", "Lansing"));
		statesList.add(new State("Minnesota", "St. Paul"));
		statesList.add(new State("Mississippi", "Jackson"));
		statesList.add(new State("Missouri", "Jefferson City"));
		statesList.add(new State("Montana", "Helena"));
		statesList.add(new State("Nebraska", "Lincoln"));
		statesList.add(new State("Nevada", "Carson City"));
		statesList.add(new State("New Hampshire", "Concord"));
		statesList.add(new State("New Jersey", "Trenton"));
		statesList.add(new State("New Mexico", "Santa Fe"));
		statesList.add(new State("New York", "Albany"));
		statesList.add(new State("North Carolina", "Raleigh"));
		statesList.add(new State("North Dakota", "Bismarck"));
		statesList.add(new State("Ohio", "Columbus"));
		statesList.add(new State("Oklahoma", "Oklahoma City"));
		statesList.add(new State("Oregon", "Salem"));
		statesList.add(new State("Pennsylvania", "Harrisburg"));
		statesList.add(new State("Rhode Island", "Providence"));
		statesList.add(new State("South Carolina", "Columbia"));
		statesList.add(new State("South Dakota", "Pierre"));
		statesList.add(new State("Tennessee", "Nashville"));
		statesList.add(new State("Texas", "Austin"));
		statesList.add(new State("Utah", "Salt Lake City"));
		statesList.add(new State("Vermont", "Montpelier"));
		statesList.add(new State("Virginia", "Richmond"));
		statesList.add(new State("Washington", "Olympia"));
		statesList.add(new State("West Virginia", "Charleston"));
		statesList.add(new State("Wisconsin", "Madison"));
		statesList.add(new State("Wyoming", "Cheyenne"));
	}

	public ArrayList<State> suggest(String input) {
		ArrayList<State> result = new ArrayList<State>();
		for (State state : statesList) {
			if ((state.getName().toLowerCase()).startsWith(input.toLowerCase()))
				result.add(state);
		}
		return result;
	}

	public List<State> getStatesList() {
		return statesList;
	}
}

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/java/org/richfaces/book/examples/common/SkinBean.java
/**
 *
 */
package org.richfaces.book.examples.common;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

/**
 * @author ishaikovsky
 */
@ManagedBean(name = "skinBean")
@SessionScoped
public class SkinBean implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -2399884208294434812L;
	private static final String SKIN_VIEW_PARAMETER = "skin";
	@ManagedProperty(value = "blueSky")
	private String skin;
	private List<String> skins;

	public SkinBean() {
		skins = new ArrayList<String>();
		skins.add("blueSky");
		skins.add("classic");
		skins.add("deepMarine");
		skins.add("emeraldTown");
		skins.add("japanCherry");
		skins.add("ruby");
		skins.add("wine");
	}

	private String getViewParameter(String name) {
		FacesContext fc = FacesContext.getCurrentInstance();
		String param = (String) fc.getExternalContext()
				.getRequestParameterMap().get(name);
		if (param != null && param.trim().length() > 0) {
			return param;
		} else {
			return null;
		}
	}

	public String getSkin() {
		String currentSkin = getViewParameter(SKIN_VIEW_PARAMETER);
		if (currentSkin != null) {
			skin = currentSkin;
		}
		return skin;
	}

	public void setSkin(String skin) {
		this.skin = skin;
	}

	public List<String> getSkins() {
		return skins;
	}

}

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/webapp/acomplete.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template.xhtml">


	<h3>Sample 1</h3>
	<rich:panel header="Using rich:autocomplete" style="width:200px">
		<h:form>
			<rich:autocomplete autocompleteList="#{autocompleteBean.suggestions}"
				mode="lazyClient" />
		</h:form>
	</rich:panel>


	<h3>Sample 2</h3>
	<rich:panel header="Using rich:autocomplete" style="width:200px">
		<h:form>
			<rich:autocomplete
				autocompleteMethod="#{autocompleteBean.autocomplete}"
				mode="cachedAjax" tokens="," minChars="2" />
		</h:form>
	</rich:panel>


	<h3>Sample 3</h3>
	<rich:panel header="Using rich:autocomplete" style="width:250px">
		<h:form>
			<rich:autocomplete autocompleteList="#{autocompleteBean.suggestions}"
				mode="lazyClient" showButton="true" selectFirst="true" />
		</h:form>
	</rich:panel>

	<h3>Sample 4</h3>
	<rich:panel header="Using rich:autocomplete" style="width:250px">
		<h:form>
			<rich:autocomplete autocompleteList="#{autocompleteBean.suggestions}"
				mode="lazyClient" showButton="true" autofill="true" />
		</h:form>
	</rich:panel>
	<h3>Sample 5</h3>

	<script>
function customFilter(subString, value){
   if(subString.length>=1) {
      if(value.indexOf(subString)!=-1) 
         return true;
      else 
         return false;
   }    
   return true;
};
</script>

	<rich:panel header="Using rich:autocomplete" style="width:250px">

		<h:form>
			<rich:autocomplete autocompleteList="#{autocompleteBean.suggestions}"
				mode="lazyClient" clientFilterFunction="customFilter" />
		</h:form>
	</rich:panel>
<style>
	.rf-au-tbl{
		width:100%
		<!--temp fix for RF issue, should not be needed soon-->
	}
</style>
	<h3>Sample 6</h3>

	<rich:panel header="Using rich:autocomplete" style="width:250px">
		<h:form>
			<rich:autocomplete layout="table"
				autocompleteMethod="#{statesSuggestionBean.suggest}" var="state"
				>
				<rich:column>
					<h:outputText value="#{state.name}" />
				</rich:column>
				<rich:column>
					<h:outputText value="#{state.capital}" />
				</rich:column>
				<rich:column>
					<h:graphicImage value="#{state.flagImage}" />
				</rich:column>
			</rich:autocomplete>
		</h:form>
	</rich:panel>
</ui:composition>

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/webapp/calendar.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template.xhtml">


	<h3>Sample 1</h3>
	<rich:panel header="Using rich:calendar">
		<rich:calendar value="#{calendarBean.today}" datePattern="dd/M/yy" />
	</rich:panel>
	<h3>Sample 2</h3>
	<rich:panel header="Using rich:calendar with time selection">
		<rich:calendar value="#{calendarBean.today}"
			datePattern="dd/M/yy HH:mm:ss" showApplyButton="true" />
	</rich:panel>
	<h3>Sample 3</h3>
	<rich:panel header="Using rich:calendar inline">
		<rich:calendar value="#{calendarBean.today}" popup="false"
			datePattern="dd/M/yy HH:mm:ss" />
	</rich:panel>
	<h3>Sample 3</h3>
	<rich:panel header="Using rich:calendar in Italian locale">
		<rich:calendar datePattern="dd/M/yy hh:mm:ss" locale="it" />

	</rich:panel>

	<h3>Sample 5</h3>
	<rich:panel header="Using rich:calendar with dataModel">
		<style>
.bdc {
	background-color: gray;
}

.wdc {
	font-weight: bold;
	font-style: italic;
}
</style>
		<h:form>
			<rich:calendar mode="ajax" popup="false" dataModel="#{calendarModel}"
				locale="en" />
		</h:form>
	</rich:panel>

	<h3>Sample 6</h3>
	<rich:panel header="Using rich:calendar client customizations">
		<style>
.everyThirdDay {
	background-color: gray;
}

.weekendBold {
	font-weight: bold;
	font-style: italic;
}
</style>
		<script type="text/javascript">
      var curDt = new Date();
      function disablementFunction(day){
         if (day.isWeekend) return false;
         if (curDt==undefined){
            curDt = day.date.getDate();
         }
         if (curDt.getTime() - day.date.getTime() &lt; 0) return true; else return false;  
      }
      function disabledClassesProv(day){
         if (curDt.getTime() - day.date.getTime() &gt;= 0) return 'rf-cal-boundary-day';
         var res = '';
         if (day.isWeekend) res+='weekendBold ';
         if (day.day%3==0) res+='everyThirdDay';
         return res;
      }
</script>
		<rich:calendar dayDisableFunction="disablementFunction"
			dayClassFunction="disabledClassesProv" />
	</rich:panel>

<rich:panel header="Using rich:calendar API">
<h:panelGrid columns="2"> 
From: 
<rich:calendar locale="en" id="c1"
onchange="#{rich:component('c2')}.setValue(#{rich:component('c1')}.getValue())" />
To: 
<rich:calendar locale="en" id="c2" />
	</h:panelGrid>
</rich:panel>

</ui:composition>

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/webapp/fileUpload.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template.xhtml">


	<h:form>
		<h:panelGrid columns="2" columnClasses="top,top">
			<rich:fileUpload fileUploadListener="#{fileUploadBean.listener}"
				maxFilesQuantity="#{fileUploadBean.uploadsAvailable}" id="upload"
				acceptedTypes="jpg, gif, png, bmp">
				<a4j:ajax event="uploadcomplete" execute="@none" render="info" />
			</rich:fileUpload>
			<h:panelGroup id="info">
				<rich:panel bodyClass="info">
					<f:facet name="header">Uploaded Files Info</f:facet>
					<rich:dataGrid columns="1" value="#{fileUploadBean.files}"
						var="file" rowKeyVar="row">
						<rich:panel>
							<h:panelGrid columns="2">
								<a4j:mediaOutput element="img" mimeType="#{file.contentType}"
									createContent="#{fileUploadBean.paint}" value="#{row}"
									style="width:100px; height:100px;" cacheable="false">
									<f:param value="#{fileUploadBean.timeStamp}" name="time" />
								</a4j:mediaOutput>
								<h:panelGrid columns="2">
									<h:outputText value="File Name:" />
									<h:outputText value="#{file.name}" />
									<h:outputText value="File Length(bytes):" />
									<h:outputText value="#{file.size}" />
								</h:panelGrid>
							</h:panelGrid>
						</rich:panel>
					</rich:dataGrid>
				</rich:panel>
			</h:panelGroup>
		</h:panelGrid>
	</h:form>

</ui:composition>

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/webapp/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j">

<body>
<ui:composition template="/templates/template.xhtml">
	<h:panelGrid columns="1">
		<h:link style="font-size:14px;" value="rich:inplaceInput" outcome="inplaceInput" />
		<h:link style="font-size:14px;" value="rich:inplaceSelect" outcome="inplaceSelect" />
		<h:link style="font-size:14px;" value="rich:autocomplete" outcome="acomplete" />
		<h:link style="font-size:14px;" value="rich:select" outcome="select" />
		<h:link style="font-size:14px;" value="rich:inputNumberSlider" outcome="inputnumberslider" />
		<h:link style="font-size:14px;" value="rich:inputNumberSpinner" outcome="inputnumberspinner" />
		<h:link style="font-size:14px;" value="rich:calendar" outcome="calendar" />
		<h:link style="font-size:14px;" value="rich:fileUpload" outcome="fileUpload" />
	</h:panelGrid>
</ui:composition>
</body>
</html>

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/webapp/inplaceInput.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:b="http://java.sun.com/jsf/composite/org.richfaces.book.tags"
	template="/templates/template.xhtml">


	<h3>Sample 1</h3>

	<rich:panel header="Using rich:inplaceInput" style="width:250px;">
		<h:form>
			<h:panelGrid columns="1">
				<rich:inplaceInput value="#{inplaceInputBean.name}"
					defaultLabel="Click to edit name" />
				<rich:inplaceInput value="#{inplaceInputBean.email}"
					defaultLabel="Click to edit email" />
			</h:panelGrid>
		</h:form>
	</rich:panel>
	<h3>Sample 2</h3>
	<rich:panel header="Using rich:inplaceInput" style="width:250px;">
		<h:form>
			<h:panelGrid columns="1">
				<rich:inplaceInput value="#{inplaceInputBean.name}"
					defaultLabel="Click to edit name" showControls="true" />
				<rich:inplaceInput value="#{inplaceInputBean.email}"
					defaultLabel="Click to edit email" showControls="true" />
			</h:panelGrid>
		</h:form>
	</rich:panel>

	<h3>Sample 3</h3>
	<h:form>
		<rich:panel header="Using rich:inplaceInput" style="width:250px;">
			<h:panelGrid columns="1">
				<rich:inplaceInput value="#{inplaceInputBean.name}"
					defaultLabel="Double click to edit name" editEvent="dblclick">
					<a4j:ajax event="change" render="out" />
				</rich:inplaceInput>
				<h:outputText value="#{inplaceInputBean.name}" id="out" />
			</h:panelGrid>
		</rich:panel>
	</h:form>
	<h3>Sample 5</h3>
	<rich:panel header="Using rich:inplaceInput" style="width:250px;">
		<rich:inplaceInput value="#{inplaceInputBean.name}" saveOnBlur="false"
			showControls="true" defaultLabel="Click to edit name" />
	</rich:panel>
	<h3>Sample 5</h3>
	<rich:panel header="Using rich:inplaceInput" style="width:250px;">
		<h:panelGrid>
			<rich:inplaceInput defaultLabel="Enter your name" id="name"
				onchange="#{rich:component('nickname')}.
          setValue(#{rich:component('name')}.getValue());" />
			<rich:inplaceInput defaultLabel="Enter your nickname" id="nickname" />
		</h:panelGrid>
	</rich:panel>
</ui:composition>

ishaikovsky-Practical-RichFaces-Book-df46ee6/inputs-selects-demo/src/main/webapp/inplaceSelect.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template.xhtml">


	<h3>Sample 1</h3>
	<rich:panel header="Using rich:inplaceSelect" style="width:200px">
		<rich:inplaceSelect value="#{inplaceSelectBean.fruit}"
			defaultLabel="Select fruit">
			<f:selectItem itemValue="1" itemLabel="Banana" />
			<f:selectItem itemValue="2" itemLabel="Cranberry" />
			<f:selectItem itemValue="3" itemLabel="Blueberry" />
			<f:selectItem itemValue="4" itemLabel="Orange" />
			<f:selectItem itemValue="5" itemLabel="Apple" />
			<f:selectItem itemValue="6" itemLabel="Strawberry" />
		</rich:inplaceSelect>
	</rich:panel>

	<h3>Sample 2</h3>
	<rich:panel header="Using rich:inplaceSelect" style="width:200px">
		<rich:inplaceSelect value="#{inplaceSelectBean.fruit}"
			inputWidth="100px" defaultLabel="Select fruit" showControls="true">
			<f:selectItem itemValue="1" itemLabel="Banana" />
			<f:selectItem itemValue="2" itemLabel="Cranberry" />
			<f:selectItem itemValue="3" itemLabel="Blueberry" />
			<f:selectItem itemValue="4" itemLabel="Orange" />
			<f:selectItem itemValue="5" itemLabel="Apple" />
			<f:selectItem itemValue="6" itemLabel="Strawberry" />
		</rich:inplaceSelect>
	</rich:panel>
	
	<h3>Sample 3</h3>
	<rich:panel header="Using rich:inplaceSelect" style="width:200px">
		<h:form>
			<h:panelGrid>
				<rich:inplaceSelect
					defaultLabel="Double click to select items type"
					value="#{inplaceSelectBean2.currentType}"
					valueChangeListener="#{inplaceSelectBean2.valueChanged}"
					editEvent="dblclick">
					<f:selectItems value="#{inplaceSelectBean2.firstList}" />
					<a4j:ajax event="change" render="second" execute="@this" />
				</rich:inplaceSelect>
				<a4j:outputPanel id="second" layout="block">
					<rich:inplaceSelect value="#{inplaceSelectBean2.currentType}"
						defaultLabel="Click to select item"
						rendered="#{not empty inplaceSelectBean2.currentType}">
						<f:selectItems value="#{inplaceSelectBean2.secondList}" />
					</rich:inplaceSelect>
				</a4j:outputPanel>
			</h:panelGrid>
		</h:form>
	</rich:panel>
</ui:composition>