ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/java/org/richfaces/book/examples/model/GameDescriptor.java
package org.richfaces.book.examples.model;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.richfaces.book.examples.util.CalendarConverter;

public class GameDescriptor extends BaseDescriptor{
	private String city;
	private String country;
	private String continent;
	private String flagName;
	private int number;
	private seasons season;
	private statuses status = statuses.passed;

	private enum statuses {
		passed, future, canceled
	};

	private enum seasons {
		Winter, Summer
	};

	private Calendar fromDate = new GregorianCalendar(Locale.US);
	private Calendar toDate = new GregorianCalendar(Locale.US);

	public int getYear() {
		return fromDate.get(Calendar.YEAR);
	}

	public String getFrom() {
		if (!status.equals(statuses.canceled)) {
			return fromDate.get(Calendar.DAY_OF_MONTH)
					+ " "
					+ fromDate.getDisplayName(Calendar.MONTH, Calendar.LONG,
							Locale.US);
		} else
			return "";
	}

	public String getTo() {
		if (!status.equals(statuses.canceled)) {
			return toDate.get(Calendar.DAY_OF_MONTH)
					+ " "
					+ toDate.getDisplayName(Calendar.MONTH, Calendar.LONG,
							Locale.US);
		} else
			return "";
	}

	public String getFlagURI() {
		return "/images/flags/" + flagName + ".png";
	}

	@XmlElement
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@XmlElement
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@XmlElement
	public String getContinent() {
		return continent;
	}

	public void setContinent(String continent) {
		this.continent = continent;
	}

	@XmlElement(name = "flag")
	public String getFlagName() {
		return flagName;
	}

	public void setFlagName(String flagName) {
		this.flagName = flagName;
	}

	@XmlElement
	public int getNumber() {
		return number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@XmlElement
	@XmlJavaTypeAdapter(value = CalendarConverter.class)
	public Calendar getFromDate() {
		return fromDate;
	}

	public void setFromDate(Calendar fromDate) {
		this.fromDate = fromDate;
	}

	@XmlElement
	@XmlJavaTypeAdapter(value = CalendarConverter.class)
	public Calendar getToDate() {
		return toDate;
	}

	public void setToDate(Calendar toDate) {
		this.toDate = toDate;
	}

	public void setSeason(seasons season) {
		this.season = season;
	}

	@XmlElement
	public statuses getStatus() {
		return status;
	}

	public void setStatus(statuses status) {
		this.status = status;
	}

	@XmlElement
	public seasons getSeason() {
		return season;
	}

}

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/java/org/richfaces/book/examples/model/SalesItem.java
package org.richfaces.book.examples.model;

import java.util.ArrayList;

import javax.faces.model.SelectItem;

public class SalesItem {
	private int productCode;
	private double proposedPrice;
	private double salesCost;
	private String reason;
	private double discount = 0;

	public ArrayList<SelectItem> getReasons() {
		ArrayList<SelectItem> reasons = new ArrayList<SelectItem>();
		if (proposedPrice != 0.0) {
			if (proposedPrice <= salesCost) {
				reasons.add(new SelectItem("Nobody Needs it"));
				reasons.add(new SelectItem("Bad Quality"));
				reasons.add(new SelectItem("Partly Broken"));
			} else {
				reasons.add(new SelectItem("Just Good"));
				reasons.add(new SelectItem("Everybody Asks for it"));
			}
		}
		return reasons;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	public double getDiscount() {
		return discount;
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public SalesItem(int productCode, double salesCost) {
		super();
		this.productCode = productCode;
		this.salesCost = salesCost;
	}

	public int getProductCode() {
		return productCode;
	}

	public void setProductCode(int productCode) {
		this.productCode = productCode;
	}

	public double getProposedGrossMargin() {
		if (proposedPrice == 0)
			return 0;
		else {
			return (proposedPrice - salesCost) / proposedPrice;
		}
	}

	public double getProposedPrice() {
		return proposedPrice;
	}

	public void setProposedPrice(double proposedPrice) {
		this.proposedPrice = proposedPrice;
	}

	public double getSalesCost() {
		return salesCost;
	}

	public void setSalesCost(double salesCost) {
		this.salesCost = salesCost;
	}
}

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/java/org/richfaces/book/examples/AirlinesBean.java
package org.richfaces.book.examples;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import org.richfaces.book.examples.model.Airline;

@ManagedBean
@RequestScoped
public class AirlinesBean {
	private List<Airline> airlines;

	@PostConstruct
	public void init() {
		airlines = new ArrayList<Airline>();
		airlines.add(new Airline("American Airlines", "AA"));
		airlines.add(new Airline("United Airlines", "UA"));
		airlines.add(new Airline("Delta", "DL"));
		airlines.add(new Airline("Northwest Airlines", "NW"));
		airlines.add(new Airline("US Airways", "US"));
		airlines.add(new Airline("Continental", "CO"));
	}

	public List<Airline> getAirlines() {
		return airlines;
	}

	public void setAirlines(List<Airline> airlines) {
		this.airlines = airlines;
	}

}

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/java/org/richfaces/book/examples/FilteringBean.java
package org.richfaces.book.examples;

import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.richfaces.book.examples.model.GameDescriptor;
import org.richfaces.model.Filter;

@ManagedBean
@ViewScoped
public class FilteringBean implements Serializable {

	private String cityFilterString;
	private String countryFilterString;
	private int centuryFilterNumber;
	private String continentFilterString="";

	public final static String[] continents = { "Europe", "Asia",
			"North America", "South America", "Oceania" };

	public Filter<GameDescriptor> getCenturyFilter() {
		return new Filter<GameDescriptor>() {
			@Override
			public boolean accept(GameDescriptor t) {
				switch (centuryFilterNumber) {
				case 19:
					return (t.getYear() >= 1800) && (t.getYear() < 1900);
				case 20:
					return (t.getYear() >= 1900) && (t.getYear() < 2000);
				case 21:
					return (t.getYear() >= 2000);
				default:
					return true;
				}
			}
		};
	}

	public void setCountryFilterString(String countryFilterString) {
		this.countryFilterString = countryFilterString;
	}

	public void setCityFilterString(String cityFilterString) {
		this.cityFilterString = cityFilterString;
	}

	public String getCountryFilterString() {
		return countryFilterString;
	}

	public String getCityFilterString() {
		return cityFilterString;
	}

	public int getCenturyFilterNumber() {
		return centuryFilterNumber;
	}

	public void setCenturyFilterNumber(int centuryFilterNumber) {
		this.centuryFilterNumber = centuryFilterNumber;
	}

	public String[] getContinents() {
		return continents;
	}

	public String getContinentFilterString() {
		return continentFilterString;
	}

	public void setContinentFilterString(String continentFilterString) {
		this.continentFilterString = continentFilterString;
	}
}

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/java/org/richfaces/book/examples/GamesHibernateBean.java
/**
 * 
 */
package org.richfaces.book.examples;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;

import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.richfaces.book.examples.common.HibernateUtils;
import org.richfaces.book.examples.model.BaseDescriptor;
import org.richfaces.book.examples.model.GameDescriptor;

@ApplicationScoped
@ManagedBean(eager = true)
public class GamesHibernateBean {

	@ManagedProperty(value = "#{gamesParser.gamesList}")
	private List<GameDescriptor> games = new ArrayList<GameDescriptor>();
	private static final String[] GAME_FIELDS = {"country", "city", "continent", "season", "number", "year"};
	@PostConstruct
	public void fillDatabase(){
		Session hibernateSession = HibernateUtils.getSessionFactory().openSession();
	    for (BaseDescriptor game : games) {
			try {
				hibernateSession.persist(game);
			}catch (HibernateException e){
				e.printStackTrace();
			}
		}
		hibernateSession.flush();
		hibernateSession.close();
	}

	public String[] getGameFields(){
		return GAME_FIELDS;
	}
	
	public void setGames(List<GameDescriptor> games) {
		this.games = games;
	}

	public List<GameDescriptor> getGames() {
		return games;
	}
}

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/java/org/richfaces/book/examples/OlympicGamesBean.java
package org.richfaces.book.examples;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.event.AjaxBehaviorEvent;

import org.richfaces.book.examples.model.BaseDescriptor;
import org.richfaces.book.examples.model.GameDescriptor;
import org.richfaces.component.UIExtendedDataTable;

@ManagedBean
@ViewScoped
public class OlympicGamesBean implements Serializable {
	@ManagedProperty(value = "#{gamesParser.gamesList}")
	private List<GameDescriptor> games = new ArrayList<GameDescriptor>();
	private Map<String, List<GameDescriptor>> gamesMap;
	private Collection<Object> selection = null;
	private List<GameDescriptor> selectedGames = null;
	private Integer currentRow;
	public Map<String, List<GameDescriptor>> getGamesMap() {
		if (gamesMap == null) {
			gamesMap = new HashMap<String, List<GameDescriptor>>();
			for (GameDescriptor game : games) {
				List<GameDescriptor> gamesFromMap = gamesMap.get(game
						.getContinent());
				if (gamesFromMap == null) {
					gamesFromMap = new ArrayList<GameDescriptor>();
				}
				gamesFromMap.add(game);
				gamesMap.put(game.getContinent(), gamesFromMap);
			}
		}
		return gamesMap;
	}
	
	public List<String> getGamesMapKeys() {
		Map<String, List<GameDescriptor>> map = getGamesMap();
		List<String> continents = new ArrayList<String>();
		Iterator<String> it = map.keySet().iterator();
		while (it.hasNext()) {
			continents.add(it.next());
		}
		Collections.sort(continents);
		return continents;
	}

	public void showSelectionDetails(AjaxBehaviorEvent event) {
		UIExtendedDataTable table = (UIExtendedDataTable) event.getComponent();
		selectedGames = new ArrayList<GameDescriptor>();
		Object storedRowKey = table.getRowKey();
		for (Object rowKey : selection) {
			table.setRowKey(rowKey);
			selectedGames.add((GameDescriptor) table.getRowData());
		}
		table.setRowKey(storedRowKey);
	}

	public BaseDescriptor getCurrentGame(){
		return (currentRow==null) ? null : games.get(currentRow);
	}
	
	public void setSelectedGames(List<GameDescriptor> selectedGames) {
		this.selectedGames = selectedGames;
	}

	public List<GameDescriptor> getSelectedGames() {
		return selectedGames;
	}

	public Collection<Object> getSelection() {
		return selection;
	}

	public void setSelection(Collection<Object> selection) {
		this.selection = selection;
	}

	public void setGames(List<GameDescriptor> games) {
		this.games = games;
	}

	public List<GameDescriptor> getGames() {
		return games;
	}

	public void setCurrentRow(Integer currentRow) {
		this.currentRow = currentRow;
	}
	
	public Integer getCurrentRow() {
		return currentRow;
	}
	
}

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/java/org/richfaces/book/examples/SortingBean.java
package org.richfaces.book.examples;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.richfaces.book.examples.model.GameDescriptor;
import org.richfaces.component.SortOrder;

@ManagedBean
@ViewScoped
public class SortingBean implements Serializable{
	private Map<String, SortOrder> sortOrders = new HashMap<String, SortOrder>();
	private Map<String, SortOrder> sortOrdersMultiple = new HashMap<String, SortOrder>();
	private List<String> sortPriorities = new ArrayList<String>();
	private static final String SORT_PROPERTY = "sortProperty";

	public void resetSorting() {
		this.sortOrdersMultiple.clear();
		this.sortPriorities.clear();
	}

	private void modifySortProperty(Map<String, SortOrder> orders,
			String sortProperty, SortOrder currentOrder) {
		if ((currentOrder == null) || (currentOrder == SortOrder.ascending)) {
			orders.put(sortProperty, SortOrder.descending);
		} else {
			orders.put(sortProperty, SortOrder.ascending);
		}
	}

	private String getSortProperty() {
		String sortProperty = FacesContext.getCurrentInstance()
				.getExternalContext().getRequestParameterMap().get(
						SORT_PROPERTY);
		return sortProperty;
	}

	public Comparator<GameDescriptor> getYearComparator() {
		return new Comparator<GameDescriptor>() {
			@Override
			public int compare(GameDescriptor o1, GameDescriptor o2) {
				return o1.getFromDate().compareTo(o2.getFromDate());
			}

		};
	}

	public void sortMultiple() {
		String sortProperty = getSortProperty();
		SortOrder currentOrder = sortOrdersMultiple.get(sortProperty);
		modifySortProperty(sortOrdersMultiple, sortProperty, currentOrder);
		if (!sortPriorities.contains(sortProperty))
			sortPriorities.add(sortProperty);
	}

	public void sort() {
		String sortProperty = getSortProperty();
		SortOrder currentOrder = sortOrders.get(sortProperty);
		sortOrders.clear();
		modifySortProperty(sortOrders, sortProperty, currentOrder);
	}

	public Map<String, SortOrder> getSortOrders() {
		return sortOrders;
	}

	public void setSortOrders(Map<String, SortOrder> sortOrders) {
		this.sortOrders = sortOrders;
	}

	public void setSortOrdersMultiple(Map<String, SortOrder> sortOrdersMultiple) {
		this.sortOrdersMultiple = sortOrdersMultiple;
	}

	public Map<String, SortOrder> getSortOrdersMultiple() {
		return sortOrdersMultiple;
	}

	public List<String> getSortPriorities() {
		return sortPriorities;
	}

	public void setSortPriorities(List<String> priorities) {
		this.sortPriorities = priorities;
	}
}

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/java/org/richfaces/book/examples/UpdateBean.java
package org.richfaces.book.examples;

import java.util.HashSet;
import java.util.Set;

import javax.faces.component.html.HtmlInputText;
import javax.faces.context.FacesContext;

public class UpdateBean {

    HtmlInputText priceRef;
    private Set<Integer> keys = null;
    
    /**
     * @return the keys
     */
    public Set getKeys() {
        return keys;
    }

    /**
     * @param keys the keys to set
     */
    public void setKeys(Set keys) {
        this.keys = keys;
    }

    public HtmlInputText getPriceRef() {
        return priceRef;
    }

    public void setPriceRef(HtmlInputText priceRef) {
        this.priceRef = priceRef;
    }
    
    public String change(){
        
        HashSet keys = new HashSet<Integer>();
        int rowKey =0
        //= getRepeater().getRowIndex()
        ;
        keys.add(rowKey);
        setKeys(keys);
        priceRef.processValidators(FacesContext.getCurrentInstance());
        priceRef.processUpdates(FacesContext.getCurrentInstance());
        return null;
    }
}

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/java/org/richfaces/book/examples/common/SkinBean.java
/**
 *
 */
package org.richfaces.book.examples.common;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

/**
 * @author ishaikovsky
 */
@ManagedBean(name = "skinBean")
@SessionScoped
public class SkinBean implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -2399884208294434812L;
	private static final String SKIN_VIEW_PARAMETER = "skin";
	@ManagedProperty(value = "blueSky")
	private String skin;
	private List<String> skins;

	public SkinBean() {
		skins = new ArrayList<String>();
		skins.add("blueSky");
		skins.add("classic");
		skins.add("deepMarine");
		skins.add("emeraldTown");
		skins.add("japanCherry");
		skins.add("ruby");
		skins.add("wine");
	}

	private String getViewParameter(String name) {
		FacesContext fc = FacesContext.getCurrentInstance();
		String param = (String) fc.getExternalContext()
				.getRequestParameterMap().get(name);
		if (param != null && param.trim().length() > 0) {
			return param;
		} else {
			return null;
		}
	}

	public String getSkin() {
		String currentSkin = getViewParameter(SKIN_VIEW_PARAMETER);
		if (currentSkin != null) {
			skin = currentSkin;
		}
		return skin;
	}

	public void setSkin(String skin) {
		this.skin = skin;
	}

	public List<String> getSkins() {
		return skins;
	}

}

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/webapp/dataGrid.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template.xhtml">


	<h3>Data Grid Sample</h3>
	<rich:panel style="width:650px" header="rich:dataGrid sample">
		<rich:dataGrid  value="#{olympicGamesBean.games}" var="game" columns="3">
			<rich:panel>
				<h:graphicImage value="#{game.flagURI}" />
				<b>#{game.country} - #{game.city}</b><br/>
				<i>#{game.from} - #{game.to}</i>
			</rich:panel>
		</rich:dataGrid>
	</rich:panel>
</ui:composition>

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/webapp/repeat.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template.xhtml">


	<h3>Creating grid using repeat</h3>
	<p>resize the browser to see the grid dynamically changing.</p>
	<a4j:repeat value="#{olympicGamesBean.games}" var="game">
		<rich:panel style="width:220px; height:60px; float:left; margin:5px;">
			<h:graphicImage value="#{game.flagURI}" />
			<b>#{game.country} - #{game.city}</b>
			<br />
			<i>#{game.from} - #{game.to}</i>
		</rich:panel>
	</a4j:repeat>
</ui:composition>

ishaikovsky-Practical-RichFaces-Book-df46ee6/iteration-demo/src/main/webapp/requestVariables.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/template.xhtml">


	<h3>rowKeyVar attribute simple usage</h3>
	<rich:panel style="width:650px" header="rich:dataTable sample">
		<rich:dataTable value="#{olympicGamesBean.games}" var="game"
			rowKeyVar="key" rows="10">
			<f:facet name="header">Olympic Games List</f:facet>
			<rich:column>#{key}</rich:column>
			<rich:column>
				<f:facet name="header">Flag</f:facet>
				<h:graphicImage value="#{game.flagURI}" />
			</rich:column>
			<rich:column>
				<f:facet name="header">City</f:facet>
				#{game.city}
			</rich:column>
			<rich:column>
				<f:facet name="header">Country</f:facet>
				#{game.country}
			</rich:column>
			<rich:column>
				<f:facet name="header">Continent</f:facet>
				#{game.continent}
			</rich:column>
			<rich:column>
				<f:facet name="header">Season</f:facet>
				#{game.season}
			</rich:column>
			<rich:column>
				<f:facet name="header">Number</f:facet>
				#{game.number}
			</rich:column>
			<rich:column>
				<f:facet name="header">Year</f:facet>
				#{game.year}
			</rich:column>
			<rich:column>
				<f:facet name="header">From</f:facet>
				#{game.from}
			</rich:column>
			<rich:column>
				<f:facet name="header">To</f:facet>
				#{game.to}
			</rich:column>
			<rich:column>
				<f:facet name="header">Note</f:facet>
				<h:outputText value="#{game.status}" />
			</rich:column>
		</rich:dataTable>
	</rich:panel>
		<h3>passing row identifier to action with rowKeyVar</h3>
	
<h:form>
   <a4j:jsFunction name="updateDetails" render="details">
      <a4j:param name="rowKey" assignTo="#{olympicGamesBean.currentRow}" />
   </a4j:jsFunction>
   <rich:panel style="width:650px" header="rich:dataTable sample">
      <h:panelGrid columns="2">
         <rich:dataTable value="#{olympicGamesBean.games}" var="game" style="cursor:pointer;"
            rowKeyVar="key" rows="5" id="table" onrowclick="updateDetails(#{key})">
            <f:facet name="header">Olympic Games List</f:facet>
			<rich:column>
				<f:facet name="header">Flag</f:facet>
				<h:graphicImage value="#{game.flagURI}" />
			</rich:column>
			<rich:column>
				<f:facet name="header">City</f:facet>
				#{game.city}
			</rich:column>
			<rich:column>
				<f:facet name="header">Country</f:facet>
				#{game.country}
			</rich:column>
			<rich:column>
				<f:facet name="header">Continent</f:facet>
				#{game.continent}
			</rich:column>
			<rich:column>
				<f:facet name="header">Season</f:facet>
				#{game.season}
			</rich:column>
			<rich:column>
				<f:facet name="header">Number</f:facet>
				#{game.number}
			</rich:column>
			<rich:column>
				<f:facet name="header">Year</f:facet>
				#{game.year}
			</rich:column>
			<rich:column>
				<f:facet name="header">From</f:facet>
				#{game.from}
			</rich:column>
			<rich:column>
				<f:facet name="header">To</f:facet>
				#{game.to}
			</rich:column>
			<rich:column>
				<f:facet name="header">Note</f:facet>
				<h:outputText value="#{game.status}" />
			</rich:column>
         </rich:dataTable>
         <rich:panel id="details" header="Selected Game:">
            <a4j:outputPanel layout="block" rendered="#{olympicGamesBean.currentGame ne null}">
               <h:graphicImage value="#{olympicGamesBean.currentGame.flagURI}" />
               <h:panelGrid columns="2">
                  <h:outputText value="Continent:" /> #{olympicGamesBean.currentGame.continent}
                  <h:outputText value="Country:" /> #{olympicGamesBean.currentGame.country}
                  <h:outputText value="City:" /> #{olympicGamesBean.currentGame.city}
                  <h:outputText value="From date:" /> #{olympicGamesBean.currentGame.from}
                  <h:outputText value="To date:" /> #{olympicGamesBean.currentGame.to}
               </h:panelGrid>
            </a4j:outputPanel>
         </rich:panel>
      </h:panelGrid>
   </rich:panel>
</h:form>
	
	<h3>iterationVar attribute</h3>
	<style>
.odd {
	background-color: #{
	richSkin
	.
	
	 
	
	additionalBackgroundColor
}

;
}
.even {
	background-color: #{
	richSkin
	.
	
	 
	
	tableSubHeaderBackgroundColor
}
;
</style>
	<h:form>
		<rich:panel style="width:650px" header="rich:dataTable sample">
			<rich:dataTable value="#{olympicGamesBean.games}" var="game"
				rowKeyVar="key" rows="10" iterationStatusVar="iter"
				rowClass="#{iter.even?'even':'odd'}">
				<f:facet name="header">Olympic Games List</f:facet>
				<rich:column>#{iter.index}</rich:column>
				<rich:column>
					<f:facet name="header">Flag</f:facet>
					<h:graphicImage value="#{game.flagURI}" />
				</rich:column>
				<rich:column>
					<f:facet name="header">City</f:facet>
				#{game.city}
			</rich:column>
				<rich:column>
					<f:facet name="header">Country</f:facet>
				#{game.country}
			</rich:column>
				<rich:column>
					<f:facet name="header">Continent</f:facet>
				#{game.continent}
			</rich:column>
				<rich:column>
					<f:facet name="header">Season</f:facet>
				#{game.season}
			</rich:column>
				<rich:column>
					<f:facet name="header">Number</f:facet>
				#{game.number}
			</rich:column>
				<rich:column>
					<f:facet name="header">Year</f:facet>
				#{game.year}
			</rich:column>
				<rich:column>
					<f:facet name="header">From</f:facet>
				#{game.from}
			</rich:column>
				<rich:column>
					<f:facet name="header">To</f:facet>
				#{game.to}
			</rich:column>
				<rich:column>
					<f:facet name="header">Note</f:facet>
					<h:outputText value="#{game.status}" />
				</rich:column>
				<f:facet name="footer">
					<rich:dataScroller />
				</f:facet>
			</rich:dataTable>
		</rich:panel>
	</h:form>
</ui:composition>